import dotenv from "dotenv";
import connectDB from "../config/db.js";
import Blog from "../models/Blog.js";
import Doctor from "../models/Doctor.js";
import Service from "../models/Service.js";
import PricingPlan from "../models/PricingPlan.js";
import Testimonial from "../models/Testimonial.js";

dotenv.config();

const seedDemoData = async () => {
  try {
    await connectDB();
    const resetDemoData = process.env.SEED_RESET === "true";

    // ------- DOCTORS (ALL from frontend - 15) -------
    if (resetDemoData) await Doctor.deleteMany({});
    const doctors = [
      { name: "Dr. Amelia Grant", slug: "amelia-grant", image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Cardiologist", shortBio: "Dr. Grant combines careful diagnostics with practical guidance that helps patients feel confident about their heart health.", biography: "With over a decade in cardiovascular care, Dr. Grant is known for turning complex results into clear, reassuring next steps. She has a particular interest in prevention and helping patients build sustainable heart-healthy habits.", qualifications: "MD, FACC", experience: "14 years experience", details: ["Heart health screening", "Preventive cardiology", "Hypertension care"], showOnHome: true, status: "active" },
      { name: "Dr. Ryan Mitchell", slug: "ryan-mitchell", image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Dental Surgeon", shortBio: "Dr. Mitchell makes every dental visit more relaxed through clear explanations and a gentle, detail-focused approach.", biography: "Dr. Mitchell blends modern dental techniques with a patient-first manner. He enjoys helping nervous patients feel at ease and believes the best outcomes begin with a conversation.", qualifications: "BDS, MDS", experience: "11 years experience", details: ["Restorative dentistry", "Smile design", "Oral surgery"], showOnHome: true, status: "active" },
      { name: "Dr. Sofia Bennett", slug: "sofia-bennett", image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Pediatrician", shortBio: "Dr. Bennett creates a warm, unhurried space where children and parents both feel heard.", biography: "Dr. Bennett brings kindness, patience, and a playful calm to every children's appointment. She works closely with parents so they leave with practical answers and peace of mind.", qualifications: "MD, FAAP", experience: "9 years experience", details: ["Child wellness visits", "Growth and development", "Family guidance"], showOnHome: true, status: "active" },
      { name: "Dr. Daniel Hayes", slug: "daniel-hayes", image: "https://plus.unsplash.com/premium_photo-1702598946543-b70f1059b055?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Orthopedic Specialist", shortBio: "Dr. Hayes helps patients return to the activities they love with precise assessment and personal recovery plans.", biography: "Dr. Hayes has spent his career helping people move with less pain and more confidence. His care plans balance clinical precision with goals that fit each patient's everyday life.", qualifications: "MBBS, FRCS", experience: "16 years experience", details: ["Joint pain", "Sports injuries", "Mobility recovery"], showOnHome: true, status: "active" },
      { name: "Dr. Olivia Carter", slug: "olivia-carter", image: "https://images.unsplash.com/photo-1580281658223-9b93f18ae9ae?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Neurologist", shortBio: "Dr. Carter brings clarity and compassion to complex neurological concerns, one step at a time.", biography: "Dr. Carter believes patients should never feel lost in medical language. Her methodical, compassionate consultations give people a clearer understanding of their neurological health.", qualifications: "MD, DM", experience: "12 years experience", details: ["Headache care", "Nerve conditions", "Neurological assessments"], showOnHome: true, status: "active" },
      { name: "Dr. Marcus Lee", slug: "marcus-lee", image: "https://plus.unsplash.com/premium_photo-1667520580687-a85c9080a9bc?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Dermatologist", shortBio: "Dr. Lee focuses on simple, evidence-led plans that support healthy skin for the long term.", biography: "Dr. Lee is passionate about practical dermatology that works in real life. He combines thorough assessment with approachable advice for patients of every age.", qualifications: "MD, DDV", experience: "10 years experience", details: ["Skin health", "Acne treatment", "Clinical dermatology"], showOnHome: true, status: "active" },
      { name: "Dr. Hannah Morgan", slug: "hannah-morgan", image: "https://images.unsplash.com/photo-1758691463582-11aea602cd4a?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "ENT Specialist", shortBio: "Dr. Morgan provides thoughtful ENT care with a focus on comfort, communication, and lasting relief.", biography: "Dr. Morgan takes time to connect the symptoms patients notice with the treatment choices available. Her warm communication style makes specialist ENT care feel approachable.", qualifications: "MBBS, DLO", experience: "13 years experience", details: ["Hearing concerns", "Sinus care", "Throat conditions"], showOnHome: true, status: "active" },
      { name: "Dr. Ethan Brooks", slug: "ethan-brooks", image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "General Physician", shortBio: "Dr. Brooks is a trusted first point of contact for clear, complete, family-centered medical care.", biography: "Dr. Brooks is valued by patients for his attentive, whole-person approach. He enjoys building long-term relationships and helping families make sense of their health over time.", qualifications: "MBBS, MRCGP", experience: "15 years experience", details: ["Everyday health", "Health checks", "Long-term care"], showOnHome: true, status: "active" },
      { name: "Dr. Grace Wilson", slug: "grace-wilson", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Family Medicine", shortBio: "Dr. Wilson partners with families at every stage of life, helping each patient make informed choices.", biography: "Dr. Wilson brings a welcoming, preventive approach to family medicine. She is especially committed to helping patients feel informed and supported at every stage of life.", qualifications: "MD, CCFP", experience: "8 years experience", details: ["Family wellness", "Preventive care", "Women's health"], showOnHome: true, status: "active" },
      { name: "Dr. Noah Foster", slug: "noah-foster", image: "https://plus.unsplash.com/premium_photo-1661740497193-6aeca35e1b01?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Internal Medicine", shortBio: "Dr. Foster takes a whole-person view of health, bringing calm expertise to complex medical needs.", biography: "Dr. Foster brings extensive internal medicine experience to patients with complex or ongoing health concerns. He is known for thoughtful diagnostic work and calm, carefully coordinated care.", qualifications: "MD, FACP", experience: "17 years experience", details: ["Complex conditions", "Chronic care", "Diagnostic review"], showOnHome: true, status: "active" },
      { name: "Dr. Christopher Dyer", slug: "christopher-dyer", image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Cardiologist", shortBio: "Dr. Dyer brings a calm, thorough approach to heart care that puts patients at ease.", biography: "Dr. Dyer is known for careful, patient-first cardiology. He takes time to explain every result and helps patients build sustainable heart-healthy routines they can actually stick with.", qualifications: "MD, FACC", experience: "12 years experience", details: ["Heart health screening", "Preventive cardiology", "Hypertension care"], showOnHome: true, status: "active" },
      { name: "Dr. Madeleine Bond", slug: "madeleine-bond", image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Oncologist", shortBio: "Dr. Bond guides patients through treatment with clarity, warmth, and unwavering support.", biography: "With over a decade in oncology, Dr. Bond helps patients navigate complex decisions with compassion. She believes in honest communication and individualized care plans at every stage of treatment.", qualifications: "MD, FACP", experience: "14 years experience", details: ["Cancer screening", "Treatment planning", "Supportive care"], showOnHome: true, status: "active" },
      { name: "Dr. Bermadette Carr", slug: "bermadette-carr", image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "General Medicine", shortBio: "Dr. Carr is a trusted first point of contact for clear, complete, family-centered medical care.", biography: "Dr. Carr is valued by patients for her attentive, whole-person approach. She enjoys building long-term relationships and helping families make sense of their health over time.", qualifications: "MBBS, MRCGP", experience: "10 years experience", details: ["Everyday health", "Preventive care", "Chronic conditions"], showOnHome: true, status: "active" },
      { name: "Dr. Nichalas Allan", slug: "nichalas-allan", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop&crop=face&auto=format&q=85", specialty: "Dental Surgeon", shortBio: "Dr. Allan makes every dental visit more relaxed through clear explanations and a gentle, detail-focused approach.", biography: "Dr. Allan blends modern dental techniques with a patient-first manner. He enjoys helping nervous patients feel at ease and believes the best outcomes begin with a conversation.", qualifications: "BDS, MDS", experience: "11 years experience", details: ["Restorative dentistry", "Smile design", "Oral surgery"], showOnHome: true, status: "active" },
    ];
    await Doctor.bulkWrite(doctors.map((doctor) => ({
      updateOne: { filter: { slug: doctor.slug }, update: { $set: doctor }, upsert: true },
    })));
    console.log(`✅ ${doctors.length} Doctors seeded`);

    // ------- SERVICES (ALL from frontend - 9) -------
    if (resetDemoData) await Service.deleteMany({});
    const services = [
      { name: "General Dentistry", slug: "general-dentistry", icon: "🩺", image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "Comprehensive oral exams, cleanings, and preventive care to keep your smile healthy and bright year-round.", fullDescription: "Our general dentistry team provides comprehensive, comfortable care that forms the foundation of lifelong oral health. From routine check-ups and professional cleanings to preventive guidance, we help you stay ahead of dental problems before they start.", details: ["Comprehensive oral examinations and digital X-rays", "Professional teeth cleaning and polishing", "Preventive care and oral hygiene education", "Fluoride treatments and sealants", "Cavity detection and early intervention"], showOnHome: true, status: "active" },
      { name: "Cosmetic Dentistry", slug: "cosmetic-dentistry", icon: "✨", image: "https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "Teeth whitening, veneers, and smile makeovers designed to give you the confident, radiant smile you deserve.", fullDescription: "Our cosmetic dentistry specialists combine artistry with dental science to create beautiful, natural-looking smiles. Using advanced materials and techniques, we design personalized treatments that enhance your appearance while maintaining excellent oral health.", details: ["Professional teeth whitening treatments", "Porcelain veneers and laminates", "Smile makeover consultations", "Composite bonding and contouring", "Invisible aligners for aesthetic alignment"], showOnHome: true, status: "active" },
      { name: "Orthodontics", slug: "orthodontics", icon: "😁", image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "Braces and clear aligners that gently straighten teeth and correct bite issues for lasting oral health.", fullDescription: "Our orthodontic department offers modern solutions for straightening teeth and correcting bite problems at any age. From traditional braces to clear aligners, we design treatment plans that fit your lifestyle and deliver lasting results.", details: ["Traditional metal braces", "Clear ceramic braces", "Invisible clear aligner therapy", "Bite correction and jaw alignment", "Retention and follow-up orthodontic care"], showOnHome: true, status: "active" },
      { name: "Oral Surgery", slug: "oral-surgery", icon: "⚕️", image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "Safe, precise surgical procedures including tooth extractions, implants, and jaw treatments performed by experts.", fullDescription: "Our oral surgery team provides safe, precise surgical solutions in a comfortable, well-equipped setting. From simple extractions to complex implant procedures, we prioritize your comfort and recovery at every stage.", details: ["Wisdom tooth extraction and impaction care", "Dental implant placement and restoration", "Bone grafting and sinus lifting", "Corrective jaw surgery", "Biopsy and oral pathology evaluation"], showOnHome: true, status: "active" },
      { name: "Pediatric Dentistry", slug: "pediatric-dentistry", icon: "👶", image: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "Gentle, friendly dental care tailored for children, building healthy habits and happy smiles from an early age.", fullDescription: "Our pediatric dental department creates a fun, fear-free environment where children feel comfortable and confident. Using child-friendly language and gentle techniques, we build positive dental experiences that last a lifetime.", details: ["Child-friendly dental examinations", "Preventive fluoride and sealant treatments", "Gentle cavity treatment for children", "Habit counseling and early orthodontic advice", "Emergency dental care for young patients"], showOnHome: true, status: "active" },
      { name: "Emergency Care", slug: "emergency-care", icon: "🚑", image: "https://images.unsplash.com/photo-1583911860205-72f8ac8ddcbe?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "Immediate relief and treatment for dental emergencies, available 24/7 so you're never left in pain.", fullDescription: "Our emergency dental care service is available around the clock to provide rapid relief from acute dental pain and trauma. We understand that dental emergencies don't keep office hours — neither do we.", details: ["24/7 emergency dental treatment", "Severe toothache and infection management", "Trauma and fracture emergency care", "Re-implantation of knocked-out teeth", "Emergency relief for swelling and abscesses"], showOnHome: true, status: "active" },
      { name: "Diagnosis", slug: "diagnosis", icon: "🩺", image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "We have implemented a number of Safety protocols and measures To ensure the safety of bath our patients and our team doctor Of dentist.", fullDescription: "Our diagnostic services use advanced technology and thorough examinations to accurately identify your dental and medical conditions, ensuring the right treatment plan from the start.", details: ["Comprehensive diagnostic examinations", "Digital X-rays and imaging", "Advanced screening and testing", "Accurate condition identification", "Personalized treatment planning"], showOnHome: true, status: "active" },
      { name: "Consultancy", slug: "consultancy", icon: "💬", image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "We have implemented a number of Safety protocols and measures To ensure the safety of bath our patients and our team doctor Of dentist.", fullDescription: "Our expert consultants provide personalized guidance and professional advice to help you make informed decisions about your health and treatment options.", details: ["One-on-one expert consultations", "Personalized treatment advice", "Second opinion services", "Comprehensive health guidance", "Follow-up consultation support"], showOnHome: true, status: "active" },
      { name: "Tracking", slug: "tracking", icon: "📊", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&h=600&fit=crop&auto=format&q=85", shortDescription: "The safety of bath our patients and our team doctor Of dentist also very good doctor for dental problem We have implemented a number.", fullDescription: "Our health tracking services help you monitor your treatment progress and recovery journey with regular updates and detailed reports, keeping you informed every step of the way.", details: ["Real-time treatment progress tracking", "Recovery milestone monitoring", "Detailed health reports", "Appointment and follow-up reminders", "Personal health record management"], showOnHome: true, status: "active" },
    ];
    await Service.bulkWrite(services.map((service) => ({
      updateOne: { filter: { slug: service.slug }, update: { $set: service }, upsert: true },
    })));
    console.log(`✅ ${services.length} Services seeded`);

    // ------- PRICING (3 show on home) -------
    if (resetDemoData) await PricingPlan.deleteMany({});
    const pricing = [
      { name: "Standard", price: "$29", billingPeriod: "/Month", description: "Perfect for individuals", features: ["10/7 Full General Service", "2 Clinic Hours", "1 Book Appointment", "5 Orthopaedic Scan"], ctaText: "Get Started", featured: false, showOnHome: true, status: "active" },
      { name: "Pro Business", price: "$39", billingPeriod: "/Month", description: "For growing families", features: ["15/7 Full General Service", "3 Clinic Hours", "2 Book Appointment", "7 Orthopaedic Scan"], ctaText: "Get Started", featured: true, showOnHome: true, status: "active" },
      { name: "Enterprise", price: "$59", billingPeriod: "/Month", description: "For complete coverage", features: ["20/7 Full General Service", "4 Clinic Hours", "3 Book Appointment", "10 Orthopaedic Scan"], ctaText: "Get Started", featured: false, showOnHome: true, status: "active" },
    ];
    await PricingPlan.bulkWrite(pricing.map((plan) => ({
      updateOne: { filter: { name: plan.name }, update: { $set: plan }, upsert: true },
    })));
    console.log(`✅ ${pricing.length} Pricing seeded`);

    // ------- TESTIMONIALS (3 show on home) -------
    if (resetDemoData) await Testimonial.deleteMany({});
    const testimonials = [
      { name: "Christopher Dyer", role: "Happy Patient", quote: "We have implemented a number of Safety protocols and measures to ensure the safety of our patients.", image: "https://plus.unsplash.com/premium_photo-1661740497193-6aeca35e1b01?w=100&h=100&fit=crop&crop=faces&auto=format&q=80", rating: 5, showOnHome: true, status: "active" },
      { name: "Madeleine Bond", role: "Happy Patient", quote: "Our facility is equipped with state-of-the-art technology to ensure the safety of our patients.", image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=faces&auto=format&q=80", rating: 5, showOnHome: true, status: "active" },
      { name: "Nichalas Allan", role: "Happy Patient", quote: "The best dental experience I've ever had. Highly recommended!", image: "https://plus.unsplash.com/premium_photo-1702598946543-b70f1059b055?w=100&h=100&fit=crop&crop=faces&auto=format&q=80", rating: 5, showOnHome: true, status: "active" },
    ];
    await Testimonial.bulkWrite(testimonials.map((testimonial) => ({
      updateOne: {
        filter: { name: testimonial.name, role: testimonial.role },
        update: { $set: testimonial },
        upsert: true,
      },
    })));
    console.log(`✅ ${testimonials.length} Testimonials seeded`);

    // ------- BLOGS (ALL 5 from frontend) -------
    if (resetDemoData) await Blog.deleteMany({});
    const blogs = [
      { title: "Emergency Medicine Research Course for Doctors", slug: "emergency-medicine-research-course", excerpt: "Advanced training program designed to equip doctors with the latest emergency medicine techniques and protocols.", content: "Emergency medicine is one of the most demanding and rewarding specialties in healthcare. Our comprehensive research course is designed to equip doctors with the latest evidence-based practices, critical decision-making skills, and hands-on training needed to excel in high-pressure emergency situations.", image: "https://plus.unsplash.com/premium_photo-1667520569693-c61155e16869?w=500&h=320&fit=crop&auto=format&q=80", author: "Dr. Sarah Mitchell", category: "Medical Education", status: "published", showOnHome: true },
      { title: "Advance Care Planning Information Session - 2023", slug: "advance-care-planning-information-session", excerpt: "Join us for an informative session about planning your future healthcare.", content: "Learn about advance care planning, making informed decisions, and ensuring your wishes are respected.", image: "https://plus.unsplash.com/premium_photo-1661286686818-5823db33959d?w=500&h=320&fit=crop&auto=format&q=80", author: "MedCare", category: "Events", status: "published", showOnHome: true },
      { title: "You Can Easily Connect to a Doctor and Make a Treatment", slug: "connect-with-doctor-for-treatment", excerpt: "Connecting with the right doctor has never been easier.", content: "Discover how easy it is to book appointments and connect with our specialist doctors online.", image: "https://plus.unsplash.com/premium_photo-1702598946543-b70f1059b055?w=500&h=320&fit=crop&auto=format&q=80", author: "MedCare", category: "Health Tips", status: "published", showOnHome: true },
      { title: "The Future of Digital Dentistry", slug: "future-of-digital-dentistry", excerpt: "Explore how digital technology is transforming modern dental care.", content: "Digital dentistry is revolutionizing how we diagnose, plan, and deliver oral healthcare. From 3D printing to AI-assisted diagnosis, the future is here.", image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=500&h=320&fit=crop&auto=format&q=80", author: "Dr. Ryan Mitchell", category: "Technology", status: "published", showOnHome: true },
      { title: "Nutrition and Dental Health", slug: "nutrition-and-dental-health", excerpt: "How your diet affects your teeth and gums.", content: "Good nutrition plays a vital role in maintaining healthy teeth and gums. Learn which foods protect your smile and which ones to avoid.", image: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=500&h=320&fit=crop&auto=format&q=80", author: "Dr. Sofia Bennett", category: "Health Tips", status: "published", showOnHome: true },
    ];
    await Blog.bulkWrite(blogs.map((blog) => ({
      updateOne: { filter: { slug: blog.slug }, update: { $set: blog }, upsert: true },
    })));
    console.log(`✅ ${blogs.length} Blogs seeded`);

    console.log("🎉 Demo data seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error(`Error seeding demo data: ${error.message}`);
    process.exit(1);
  }
};

seedDemoData();