export const departmentDetails = [
  {
    slug: "cardiology",
    name: "Cardiology",
    image: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Thoughtful heart care, from routine screening to specialist review.",
    about: "Our cardiology department provides comprehensive cardiac care combining advanced diagnostic technology with a patient-first approach. From routine heart health screenings to complex condition management, our specialist team designs care plans around your unique needs.",
    services: [
      "Heart health screening and risk assessment",
      "Preventive cardiology and lifestyle guidance",
      "ECG, echocardiography, and stress testing",
      "Hypertension and cholesterol management",
      "Cardiac rehabilitation programs",
    ],
    specialists: ["Dr. Christopher Dyer", "Dr. Amelia Grant"],
    image2: "https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "dental-care",
    name: "Dental Care",
    image: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Comfort-focused preventive, restorative, and cosmetic dentistry.",
    about: "Our dental care team offers a full spectrum of services under one roof, combining gentle, personalized treatment with modern technology. From routine check-ups to complete smile makeovers, we ensure every visit feels comfortable and stress-free.",
    services: [
      "Comprehensive oral examinations and cleaning",
      "Preventive care and patient education",
      "Restorative treatments including fillings and crowns",
      "Cosmetic procedures for a brighter smile",
      "Dental implants and replacement options",
    ],
    specialists: ["Dr. Ryan Mitchell", "Dr. Nichalas Allan"],
    image2: "https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "pediatrics",
    name: "Pediatrics",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Gentle care that helps children feel confident at every visit.",
    about: "Our pediatric department creates a warm, welcoming environment designed to make healthcare a positive experience for children and their families. We combine medical expertise with playful, patient communication to build lifelong healthy habits.",
    services: [
      "Newborn and well-child visits",
      "Growth and developmental assessments",
      "Vaccinations and immunizations",
      "Childhood illness diagnosis and treatment",
      "Nutrition and wellness guidance for families",
    ],
    specialists: ["Dr. Sofia Bennett"],
    image2: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "orthopedics",
    name: "Orthopedics",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Personalized support for bones, joints, mobility, and recovery.",
    about: "Our orthopedic team focuses on helping patients move with less pain and more confidence. Whether recovering from injury or managing chronic joint conditions, we provide precise diagnosis, treatment, and rehabilitation plans tailored to your lifestyle.",
    services: [
      "Joint pain diagnosis and treatment",
      "Sports injury assessment and recovery",
      "Fracture care and management",
      "Physical therapy and rehabilitation",
      "Mobility recovery programs",
    ],
    specialists: ["Dr. Daniel Hayes"],
    image2: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "neurology",
    name: "Neurology",
    image: "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Clear guidance for conditions affecting the brain and nervous system.",
    about: "Our neurology department provides comprehensive evaluation and management of conditions affecting the brain and nervous system. We believe patients should never feel lost in medical language, so our consultations are clear, methodical, and compassionate.",
    services: [
      "Headache and migraine treatment",
      "Nerve condition evaluation and management",
      "Neurological assessments and diagnostic testing",
      "Memory and cognitive health evaluations",
      "Epilepsy and seizure disorder care",
    ],
    specialists: ["Dr. Olivia Carter"],
    image2: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "dermatology",
    name: "Dermatology",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Evidence-led care for healthy skin, hair, and nails.",
    about: "Our dermatology department focuses on practical, evidence-led care that works in real life. From common skin concerns to specialized treatments, we provide thorough assessment and approachable advice for patients of every age.",
    services: [
      "Skin health assessments and screenings",
      "Acne treatment and management",
      "Hair and nail condition care",
      "Eczema, psoriasis, and allergy care",
      "Minor dermatological procedures",
    ],
    specialists: ["Dr. Marcus Lee"],
    image2: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "ent-care",
    name: "ENT Care",
    image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Specialist treatment for ear, nose, throat, and hearing concerns.",
    about: "Our ENT department provides thoughtful care with a focus on comfort, communication, and lasting relief. We connect the symptoms patients notice with the treatment choices available, making specialist ENT care feel approachable.",
    services: [
      "Hearing assessments and management",
      "Sinus and allergy treatment",
      "Throat condition care",
      "Ear infection treatment",
      "Balance and dizziness evaluation",
    ],
    specialists: ["Dr. Hannah Morgan"],
    image2: "https://images.unsplash.com/photo-1584395632530-dd3b20c44f1c?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "general-medicine",
    name: "General Medicine",
    image: "https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "A trusted first point of care for everyday health needs.",
    about: "Our general medicine department is your trusted first point of contact for everyday health needs. We provide attentive, whole-person care that builds long-term relationships and helps families understand their health over time.",
    services: [
      "Routine health screenings and check-ups",
      "Everyday illness diagnosis and treatment",
      "Chronic condition management",
      "Preventive health counseling",
      "Health education and lifestyle guidance",
    ],
    specialists: ["Dr. Ethan Brooks", "Dr. Grace Wilson"],
    image2: "https://images.unsplash.com/photo-1504813184591-01572f98c85f?w=600&h=400&fit=crop&auto=format&q=80",
  },
];