export const serviceDetails = [
  {
    slug: "general-dentistry",
    title: "General Dentistry",
    image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Comprehensive oral exams, cleanings, and preventive care to keep your smile healthy and bright year-round.",
    about: "Our general dentistry team provides comprehensive, comfortable care that forms the foundation of lifelong oral health. From routine check-ups and professional cleanings to preventive guidance, we help you stay ahead of dental problems before they start.",
    services: [
      "Comprehensive oral examinations and digital X-rays",
      "Professional teeth cleaning and polishing",
      "Preventive care and oral hygiene education",
      "Fluoride treatments and sealants",
      "Cavity detection and early intervention",
    ],
    specialists: ["Dr. Ryan Mitchell", "Dr. Nichalas Allan"],
    image2: "https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "cosmetic-dentistry",
    title: "Cosmetic Dentistry",
    image: "https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Teeth whitening, veneers, and smile makeovers designed to give you the confident, radiant smile you deserve.",
    about: "Our cosmetic dentistry specialists combine artistry with dental science to create beautiful, natural-looking smiles. Using advanced materials and techniques, we design personalized treatments that enhance your appearance while maintaining excellent oral health.",
    services: [
      "Professional teeth whitening treatments",
      "Porcelain veneers and laminates",
      "Smile makeover consultations",
      "Composite bonding and contouring",
      "Invisible aligners for aesthetic alignment",
    ],
    specialists: ["Dr. Nichalas Allan"],
    image2: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "orthodontics",
    title: "Orthodontics",
    image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Braces and clear aligners that gently straighten teeth and correct bite issues for lasting oral health.",
    about: "Our orthodontic department offers modern solutions for straightening teeth and correcting bite problems at any age. From traditional braces to clear aligners, we design treatment plans that fit your lifestyle and deliver lasting results.",
    services: [
      "Traditional metal braces",
      "Clear ceramic braces",
      "Invisible clear aligner therapy",
      "Bite correction and jaw alignment",
      "Retention and follow-up orthodontic care",
    ],
    specialists: ["Dr. Ryan Mitchell"],
    image2: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "oral-surgery",
    title: "Oral Surgery",
    image: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Safe, precise surgical procedures including tooth extractions, implants, and jaw treatments performed by experts.",
    about: "Our oral surgery team provides safe, precise surgical solutions in a comfortable, well-equipped setting. From simple extractions to complex implant procedures, we prioritize your comfort and recovery at every stage.",
    services: [
      "Wisdom tooth extraction and impaction care",
      "Dental implant placement and restoration",
      "Bone grafting and sinus lifting",
      "Corrective jaw surgery",
      "Biopsy and oral pathology evaluation",
    ],
    specialists: ["Dr. Ethan Brooks", "Dr. Daniel Hayes"],
    image2: "https://images.unsplash.com/photo-1583911860205-72f8ac8ddcbe?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "pediatric-dentistry",
    title: "Pediatric Dentistry",
    image: "https://images.unsplash.com/photo-1584515933487-779824d29309?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Gentle, friendly dental care tailored for children, building healthy habits and happy smiles from an early age.",
    about: "Our pediatric dental department creates a fun, fear-free environment where children feel comfortable and confident. Using child-friendly language and gentle techniques, we build positive dental experiences that last a lifetime.",
    services: [
      "Child-friendly dental examinations",
      "Preventive fluoride and sealant treatments",
      "Gentle cavity treatment for children",
      "Habit counseling and early orthodontic advice",
      "Emergency dental care for young patients",
    ],
    specialists: ["Dr. Sofia Bennett"],
    image2: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "emergency-care",
    title: "Emergency Care",
    image: "https://images.unsplash.com/photo-1583911860205-72f8ac8ddcbe?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "Immediate relief and treatment for dental emergencies, available 24/7 so you're never left in pain.",
    about: "Our emergency dental care service is available around the clock to provide rapid relief from acute dental pain and trauma. We understand that dental emergencies don't keep office hours — neither do we.",
    services: [
      "24/7 emergency dental treatment",
      "Severe toothache and infection management",
      "Trauma and fracture emergency care",
      "Re-implantation of knocked-out teeth",
      "Emergency relief for swelling and abscesses",
    ],
    specialists: ["Dr. Grace Wilson", "Dr. Christopher Dyer"],
    image2: "https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "diagnosis",
    title: "Diagnosis",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "We have implemented a number of Safety protocols and measures To ensure the safety of bath our patients and our team doctor Of dentist.",
    about: "Our diagnostic services use advanced technology and thorough examinations to accurately identify your dental and medical conditions, ensuring the right treatment plan from the start.",
    services: [
      "Comprehensive diagnostic examinations",
      "Digital X-rays and imaging",
      "Advanced screening and testing",
      "Accurate condition identification",
      "Personalized treatment planning",
    ],
    specialists: ["Dr. Christopher Dyer", "Dr. Nichalas Allan"],
    image2: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "consultancy",
    title: "Consultancy",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "We have implemented a number of Safety protocols and measures To ensure the safety of bath our patients and our team doctor Of dentist.",
    about: "Our expert consultants provide personalized guidance and professional advice to help you make informed decisions about your health and treatment options.",
    services: [
      "One-on-one expert consultations",
      "Personalized treatment advice",
      "Second opinion services",
      "Comprehensive health guidance",
      "Follow-up consultation support",
    ],
    specialists: ["Dr. Madeleine Bond", "Dr. Bermadette Carr"],
    image2: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&h=400&fit=crop&auto=format&q=80",
  },
  {
    slug: "tracking",
    title: "Tracking",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&h=600&fit=crop&auto=format&q=85",
    tagline: "The safety of bath our patients and our team doctor Of dentist also very good doctor for dental problem We have implemented a number.",
    about: "Our health tracking services help you monitor your treatment progress and recovery journey with regular updates and detailed reports, keeping you informed every step of the way.",
    services: [
      "Real-time treatment progress tracking",
      "Recovery milestone monitoring",
      "Detailed health reports",
      "Appointment and follow-up reminders",
      "Personal health record management",
    ],
    specialists: ["Dr. Nichalas Allan", "Dr. Christopher Dyer"],
    image2: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop&auto=format&q=80",
  },
];
