import { useState } from "react";
import { useAuth } from "../../../context/AuthContext";
import { api } from "../../../api";

export default function UserProfile() {
  const { user, updateUser } = useAuth(); const [name, setName] = useState(user?.name || ""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [profileImage, setProfileImage] = useState(user?.profileImage || ""); const [message, setMessage] = useState("");
  const save = async (event) => { event.preventDefault(); try { const data = await api.request("/auth/profile", { method: "PUT", body: JSON.stringify({ name, currentPassword, newPassword, profileImage }) }); updateUser(data.user); setMessage("Profile updated successfully."); setCurrentPassword(""); setNewPassword(""); } catch (err) { setMessage(err.message); } };
  return <div className="w-full"><div className="mb-8"><h2 className="text-2xl font-heading text-brand-navy">My Profile</h2><p className="mt-1 text-sm text-brand-gray">Update your username, profile picture, or password.</p></div><form onSubmit={save} className="rounded-2xl bg-white shadow-md p-6 sm:p-8"><div className="flex items-center gap-4 border-b border-gray-100 pb-6"><div className="h-16 w-16 rounded-full overflow-hidden bg-brand-green flex items-center justify-center text-2xl font-bold text-white shrink-0">{profileImage ? <img src={profileImage} className="h-full w-full object-cover" /> : user?.name?.charAt(0)}</div><div><h3 className="text-xl font-heading text-brand-navy">{name || "Your name"}</h3><p className="text-sm text-brand-gray">{user?.email}</p></div></div><div className="mt-7 grid lg:grid-cols-2 gap-6"><div className="space-y-5"><div><label className="block text-xs font-semibold text-brand-navy mb-2">Username</label><input value={name} onChange={e => setName(e.target.value)} required className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /></div><div><label className="block text-xs font-semibold text-brand-navy mb-2">Profile image URL</label><input value={profileImage} onChange={e => setProfileImage(e.target.value)} placeholder="Paste image URL (optional)" className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /></div></div><div className="space-y-5 lg:border-l lg:border-gray-100 lg:pl-6"><div><h3 className="text-lg font-heading text-brand-navy">Change password</h3><p className="mt-1 text-xs text-brand-gray">Leave empty to keep your current password.</p></div><input type="password" value={currentPassword} onChange={e => setCurrentPassword(e.target.value)} placeholder="Current password" className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /><input type="password" value={newPassword} onChange={e => setNewPassword(e.target.value)} placeholder="New password" minLength="6" className="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm" /></div></div>{message && <p className="mt-5 text-sm text-brand-green">{message}</p>}<button className="mt-7 bg-brand-green hover:bg-brand-green-dark text-white px-7 py-3 rounded-xl text-sm font-semibold">Save changes</button></form></div>;
}
